### PR TITLE
fixed NoSuchMethodError: The getter 'stream' was called on null

### LINKED ISSUE #3: The getter 'stream' was called on null
When trying to connect with a dead server, shows this error 
```Another exception was thrown: NoSuchMethodError: The getter 'stream' was called on null.```

### PR DESCRIPTION
**Pull request by GajjarMiten**
##  Description

This PR fixed the error NoSuchMethodError: The getter 'stream' was called on null.

## Related Issue
Fixes #3

### CODE REVIEW

File: lib/utils/store.dart [hunk 1]
```diff
@@ -21,18 +21,32 @@ class User {
...
-    var body = {
-      "username": username
-    };
-
-    await http.post(url, body: body);
-
-    this.user.connect(username);
-    this.channel = IOWebSocketChannel.connect("ws://$ipAddr:41431/ws/$username");
+  Future<http.Response> createConnection(String ipAddr, String username) async {
+    var url = "https://$ipAddr:41431/register";
```
Comment (janvig) [inline lib/utils/store.dart]: It hasn't reached a stable version yet so let's keep it `http` for now since we are trying to connect with a local server that can be running on the user's computer. It is a breaking change so will take a while and it **may** allow making connections with servers on the same network, if not then we'll have to find another workaround.

Comment (GajjarMiten) [reply lib/utils/store.dart]: Yes got it.
I have made changes, could you please review it?

**Review by janvig — APPROVED** [review]
All set :rocket:

**Comment by sanket143** [comment]
give @GajjarMiten 25 points
